In [1]:
#pip install statsmodels
#conda install xgboost

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
from scipy.stats import ttest_ind
import statsmodels.stats.power as smp
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import xgboost as xgb

In [3]:
data = pd.read_csv('House Prices.csv')

In [4]:
data.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [5]:
data.isna()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4596,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4597,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4598,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4599,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [6]:
data['price'].mean()

551962.9884732141

# Hypothesis Testing

Performing Hypothisis testing for the Alpha at 5% for the house prices that house mean house price value of $551963 if the P value is for the alpha of 0.05 is less then we will refect the null hypothesis

In [7]:
alpha = 0.5
null_hypothesis = data['price'].mean()

In [8]:
# Here we are performing T-Test for the hypothesis testing
t_stat, p_value  = stats.ttest_1samp(data['price'],null_hypothesis)

In [9]:
if p_value<alpha :
    print("Reject the Null Hypothesis")
else:
    print("Fail to reject null hypothesis")

Fail to reject null hypothesis

Here we can see that we fail to reject the Null hypothesis , that means our house price data is consistent with an assumption that the population mean is equal to $551962.9884732141

# Alpha/ Beta Testing

In [10]:
grp_a = data['price'].iloc[:2300]
grp_b = data['price'].iloc[2300:]

In [11]:
grp_a

0        313000.0
1       2384000.0
2        342000.0
3        420000.0
4        550000.0
          ...
2295     200000.0
2296     295000.0
2297     580379.0
2298     875000.0
2299     515000.0
Name: price, Length: 2300, dtype: float64

In [12]:
grp_b

2300    599000.000000
2301    285000.000000
2302    290000.000000
2303    355000.000000
2304    381000.000000
            ...
4595    308166.666667
4596    534333.333333
4597    416904.166667
4598    203400.000000
4599    220600.000000
Name: price, Length: 2300, dtype: float64

In [13]:
t_stat1,p_value1 = ttest_ind(grp_a,grp_b)
print("T-statistics",t_stat1)
print("P-Value",p_value1)

T-statistics -0.6048022124721948
P-Value 0.5453402677120369

In [14]:
#statistical Power in order to calculate the difference between two groups
# n = len(data)
# effect_size = np.mean(grp_a) - np.mean(grp_b)
# alpha = 0.05
# ratio = 1

In [15]:
# # power of the test
# power = smp.TTestIndPower().power(effect_size=effect_size,nobs1=n*ratio,alpha = alpha,ratio = ratio,alternative="two-sided")
# print("Power of the test",power)

# Machine Learning Models like Regression, Classification

In [16]:
data.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [17]:
X = data.drop(['date','price','street','city','statezip','country'],axis = 1)
y = data['price']

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [19]:
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [20]:
prediction = lr.predict(X_test)
prediction

array([ 304863.38578053,  326517.06991506, 1071762.53630093,
        546241.40097351,  379799.98321077,  605792.93622748,
        481263.5712065 ,  418905.11058129,  509341.50791915,
        530852.97588251,  682958.97641215,  414525.3613005 ,
        836974.40259906,  416500.85730824,  367263.43388217,
        702908.51672183,  677878.69067825,  515539.32998912,
       1019380.63891402,  861119.79490726, 1364866.21814694,
        637439.70016772,  634739.56666336,  470424.21250257,
        162037.15383025,  232831.37648233,  669951.05071601,
        884080.66695004,  263027.22577195,  974954.64229475,
       1883342.16391336,  481510.29664849, 1275554.6525372 ,
        430994.93178858,  180366.40705409,  339240.17357412,
        792335.74094022, 1011053.14613369,  238036.2092767 ,
        543438.66040774,  423414.50597284,  243429.92107964,
        390151.3007404 ,  361322.67375674,  320343.34636007,
        317865.29287637,  469559.60646618,  573249.20158967,
        828966.75691609,  455286.46524102, 1213320.90955266,
        379278.14711404,  456992.22261157,  640657.0481953 ,
        281556.43960246,  355542.07843759,  977771.43585346,
        763946.83314539, 1012025.8315006 ,  286955.28768713,
        555835.61977616,  928556.49045177,  231280.25911117,
        910032.99943182,  769535.57238158,  562525.1115253 ,
        637463.19873756,  570860.06751283,  345837.0106487 ,
        295419.81242339, 1006508.17902277,  402155.24325432,
        367461.9126622 ,  870934.05572679,  349348.42679596,
        763750.32849311,  540526.04457527,  766712.74407826,
        477684.93612126,  229401.15552778,  563785.76349417,
        309224.69194748,  523372.9973662 ,  826306.84346155,
        359320.20890576,  272129.52465171,  384417.05303361,
        546211.65031845,  903097.91201913,  320858.51775883,
        845866.1431148 ,  285079.54355463,  304814.59399449,
        467565.73525599,  650291.30744735, 1143004.88154432,
        724309.90300224,  709038.64541321,  453017.90997358,
        476379.49824259,  501727.98469158,  380642.13128013,
        240381.51165489,  461838.22853625,  481557.05182969,
        948783.75966243,  660133.0457979 ,  290276.92365824,
        661221.23213656,  583725.99937401,  602486.70354448,
        575596.86113852,  294563.7707579 ,  388805.6412046 ,
        995324.89932147,  538263.87912044,  523482.02345956,
        679531.93989525,  468848.01606415,  355998.0095917 ,
        713098.11614061,  620513.40146275,  734301.37951923,
        419909.42644303,  261870.25647555,  309599.66817932,
        856156.96756055,  462619.44780873,  316249.45792271,
        619234.91457498,  410096.51028041,  421977.58123594,
        740906.84546304,  368934.95325227,  275512.17368778,
        339244.67408885,  326790.34090698,  311169.8249717 ,
        607281.77186497,  724274.31637021,  358795.31130745,
        438734.57557094,  534109.63529707,  347968.72983392,
        962847.15890306,  843264.69724113,  247961.87220168,
        308624.05587779,  264645.83681688,  295180.66112273,
        403004.70280148,  715896.00537896,  709231.24879241,
        292807.56878752,  762270.71401035,  643055.17920435,
       1258126.75340634,  752499.84100359,  401925.78179456,
        251971.95660311,  359391.79025331,  940276.60823417,
        382562.36382342,  615368.51381235,  515703.35748954,
        594174.02274637,  842382.44396642,  308053.10540562,
        621516.05939238,  735550.62370151,  205470.86500566,
        466628.87635706,  873755.61292321,  347428.26709859,
        687181.77023257,  817197.54329577,  295237.22961939,
        663079.56797463,  669745.66313066,  334933.90721232,
        445168.97222069,  212192.2795785 ,  710770.66945557,
        385172.09260547,  380602.41200769, 1671266.3555786 ,
        693829.18041387,  340391.76908033,  630592.15427278,
        427606.62802454,  860962.99567356,  234677.28552314,
        236298.55856068,  647974.51481865,  513595.81813459,
       1495235.91491019,  795716.01922661,  970101.04401532,
        236515.8786169 ,  205976.1791548 ,  328649.2455733 ,
        599767.98478187,  161623.58859482,  591869.28189171,
        464183.13480302,  513400.2400499 ,  626164.24935859,
        538041.36304023,  331152.31562654,  816335.5078748 ,
        593225.64834897,  389452.46780558,  880687.09269038,
        480694.10881633,  557372.68907541,  377656.62793017,
        281998.24237927,  349371.21341268,  422950.87816738,
        353938.22060079,  710692.54097466,  659093.12027764,
        254629.33523889,  555123.39443175,  688125.60298326,
        547676.41950933,  363317.10585672,  334273.88910186,
        548334.22184754,  712203.51998906,  248058.76456346,
        354194.65822131,  296171.39441815,  451205.47091796,
        648109.3665013 ,  709124.98888438, 1289448.47850992,
        290094.31038017,  285637.30762789,  353669.55744398,
        544639.52794252,  504083.08204831,  565911.7877615 ,
        313289.58680402,  254998.67844752,  570794.91092583,
        482032.66178423,  551030.57171699,  371889.15542462,
        382199.67711397,  243282.8329887 ,  130162.34899384,
        450633.50598167,  372246.93314186,  342553.26291115,
       1318129.04511773,  208538.80148266,  793719.75475554,
        581609.08164069,  358389.67813797,  162309.76012081,
        494467.57587951,  344484.48489257,  311498.3799776 ,
        506684.53189404,  572658.62918427,  726223.66978109,
        364395.07224353,  386904.6586581 ,  254419.20836787,
       1109090.23790883,  719615.28030943,  260734.38055064,
        879122.19827604,  394814.78468757,  287963.1625052 ,
        330188.20070807,  580943.65958484,  855375.07131319,
        313714.65770229,  394928.79591011,  395230.54460012,
        537149.03037449,  739095.60989216,  458637.48726432,
        302156.40348371,  780449.53768577,  551108.9905645 ,
       1102977.66959434,  247782.68424567,  254673.92346326,
        529500.2865675 ,  441877.3762131 ,  719485.84905128,
        364373.17509036,  571174.15928874,  853680.36800738,
        689587.79264265,  314072.87487028,  512657.57817689,
        365129.72029791,  750378.49400224,  471570.81639344,
        587779.09592328,  576120.83232985,  585924.79061442,
        193553.31729767,  282802.82264509,  452779.86505415,
        594246.25503794, 3747679.54681824, 1637256.81673019,
       1156970.48270157, 1012440.6734762 ,  465966.64125336,
       1063456.65680829,  253833.22993085,  465355.94092565,
        916081.52451192,  378552.23503899,  563455.81196697,
        274346.45730096,  471101.25387304,  743148.40653096,
        437856.5202133 ,  366734.60225408,  288176.10983705,
        360667.87566626,  676203.79765281,  443257.30987704,
        291244.43600934,  643934.12121546,  356597.40770628,
        497350.94439283, 1000109.24014799,  173446.93487016,
        463991.43529459,  719851.84366777,  419864.56440111,
       1322674.18477516,  367171.03653652,  326407.98054273,
        327025.443587  ,  574144.59642675,  864845.06843291,
        299733.93861351,  522813.83667141,  838827.54109372,
        424913.60827541,  270486.46786429,  601666.39623304,
        246626.78562437, 1149590.80227558,  375392.61177257,
        393153.22563158,  186187.20591467,  384061.37066553,
        614443.50208849,  461418.19362057,  657215.10929115,
        586644.12171014,  454716.25405971, 1191021.35405106,
        331948.33304541,  557095.53793671,  808895.11216744,
        723692.68778779,  657688.13353307,  486897.57813323,
        292008.02496062,  459382.59556702,  619888.02588245,
        442195.0890013 ,  317122.36641292,  555183.7862313 ,
        561550.11563745,  251622.13946963,  760500.71657378,
        423722.54383669,  501938.09602325,  454082.79868944,
        302931.1709672 ,  258240.28348359,  542860.05300284,
        210332.74789806,  610756.40027399,  403275.82341807,
        942460.67673432,  415271.99064693,  347858.20683395,
        274980.64283842,  377943.79292611,  250048.03213683,
        640028.5954326 ,  157075.20406851,  849682.33005262,
        519103.58432852,  595184.2219973 ,  487084.6391556 ,
        464384.74985923,  339817.78031649,  251070.94564393,
       1059006.33313233,  701917.80480685,  872187.48323681,
        390399.38512133,  885843.88514452,  592752.9679551 ,
        341408.74905072,  601939.54146385,  496161.61052755,
        943525.70816046,  367671.44360278,  639713.66557806,
        536447.13293782,  563785.76349417,  260548.32023559,
        839482.02560396,  427088.28242488,  371895.31856819,
        536735.95696342,  231820.42689825,  463428.77640907,
        595640.39146898,  655048.21685934,  482140.45403889,
        720001.39109082,  432373.52242789,  209601.71314213,
        217535.89123727,  247114.74220656,  659189.27343381,
        510359.40600167,  395408.14138138,  501814.41950945,
        474163.98597894,  525377.5022839 ,  197801.93927659,
        195248.53514866,  591958.34204007,  740908.24338141,
        282767.41384523,  211823.83814543,  391762.30704493,
        227033.43526074,  279113.32962318,  197157.96756653,
        647834.30994708, 1078736.16693837, 1124705.06726569,
        607665.52684598,  851471.06460994,  751128.93783339,
        228370.75656861,  523876.23479936,  605968.10671432,
        380344.1403871 ,  686998.77841111,  686740.81454998,
        644735.12657218,  283788.42110726,  494782.31740239,
        305715.52526099,  631258.59508786,  286327.39219012,
       1399339.33495284,  287934.5077843 , 1181722.01770654,
        482445.99243702, 1219255.61502813,  196012.44451794,
        782289.6171924 ,  364224.05318788,  270208.20855712,
        365058.35316162,  619484.75777253,  650611.74396916,
       1350829.47252268,  375964.11285464,  498764.33812168,
        385647.04549277, 1073533.75667768,  695307.7254153 ,
        699163.81065109,  412315.51777986,  515599.06328149,
        705674.44705652,  224159.83840033,  271908.2830751 ,
        369571.93930194,  595511.19347978,  385351.24662632,
        663905.42188701,  244908.11791608,  328880.96337341,
        183321.67566964,  722011.39335946,  578489.60575108,
        487853.52317452,  425144.15791342,  669800.71470686,
        377376.57927222,  326039.02948341,  227931.41250212,
        468966.96201669,  737178.21852629,  382908.13514465,
        421452.40136267,  455173.37253156,  280856.84864569,
        322803.38329765,  619440.34383019, 1107208.48055676,
        820744.96209317,  565768.29278417,  598069.8077114 ,
        422687.90365991,  376198.24111256,  454250.15715728,
        707158.83528143,  349503.19206452,  499190.7104437 ,
        247203.44497317,  307664.50570899,  546731.17260183,
        261303.87521309,  852754.41319636,  188024.41745885,
        166007.01266926,  344981.27950148,  324142.33681466,
        617064.36388168,  296989.58001426,  883215.87144804,
        502834.28849109,  516437.18671858,  413915.76660066,
        828985.14801776,  542311.59275419,  211889.1186577 ,
        521709.45327636,  377786.83526182,  185313.6645301 ,
        442272.74877082,  230129.22957032,  637630.80945169,
        316412.36182819,  737837.77234149,  400185.20740413,
        787277.27746289,  301076.50114965,  426083.13018165,
        680328.57409746,  459497.35241735,  257477.80806655,
        567695.09624893,  345116.48310143,  655437.74907024,
        408280.07772402,  412595.62049522,  411979.9085884 ,
        351688.06418104,  331277.76218929,  566054.18684599,
        234632.20318679,  302875.0081868 , 1119428.80942001,
        698512.27137037, 1993475.76057353,  407263.11509423,
        673035.62345771,  453782.23608864,  742215.65731276,
        636083.30377529,  247035.6731149 ,  586247.28280142,
        686364.05476285,  870113.76565062,  734178.10569879,
        152280.93158766,  275319.36900447,  170756.15040165,
        510259.96603914, 1170826.09125814,  520995.51208301,
        375058.51151154,  598509.47348766,  485027.51532327,
       1403645.47893128,  329564.50636229,  399175.4366442 ,
       1363505.56189647,  248513.01732468,  217990.94513315,
        572958.5797169 ,  632046.84570385,  446844.6074418 ,
        207164.54527014,  657332.20091628,  540277.97031732,
        408359.19173807,  237196.3331554 ,  246311.03669684,
        337762.06474789,  476406.69721453,  111892.43957047,
        616205.9803016 ,  783059.80656621,  741518.17225648,
        581235.588782  ,  147165.15172819,  833868.20373638,
        252488.88520815,  608341.17502821,  752950.24297929,
        670980.11933519,  414935.5904533 ,  769396.2066639 ,
        659035.60129094, 1036037.28905242,  343547.28706973,
        662924.14231133, 1124894.75877449,  578427.5932065 ,
        581325.53446139,  371478.24742383,  462867.58720091,
        927036.00272527, 1029377.72378007,  621419.64593557,
        508290.58493154,  199636.06108273,  574136.89802069,
        723026.19745093,  630493.45353118,  466079.14618308,
        292846.01722567,  216433.18296243,  505298.49197978,
        705110.26595255,  759661.28701515,  292604.15669835,
        532733.94822787,  830041.94300542,  228557.45036843,
        282274.33048442,  530715.37580343,  522246.81152076,
       1259473.12632752,  575401.65476279,  251800.09481376,
        521708.46409751,  365554.91847637,  559232.14098427,
       1009468.02423332, 1018713.38089431,  302358.62782869,
        226740.07061436,  811408.81880628,  205034.45022669,
        552251.99666763,  450440.23413971,  254571.0651204 ,
        623372.21794512,  427167.83917257,  672649.54728199,
        436908.07951064,  383810.94914879,  587737.36261508,
        481917.83620934,  564368.76706416,  809845.2413152 ,
        403347.60829368, 1007160.86634261,  871843.37304355,
        442808.65832644,  896592.95932317,  952415.03154814,
        373549.12635194,  492945.04062961,  628450.49126518,
        458602.13956389,  356838.91588729,  509086.21139672,
        540767.27360066,  219302.95494354,  347809.98212794,
        272430.34180462,  437593.34482486,  777175.23249577,
        589499.03455766, 1094978.54029038,  569596.58083943,
        713306.19330193,  573586.56484183,  255701.56701572,
        513874.51083599,  264901.72924126,  204029.18248275,
        551974.63545397,  762792.64177456, 1069710.75246007,
        391012.10326699,  785447.22518778,  930912.33055821,
        669289.76822299,  526907.22933066,  288643.23577344,
        482018.812257  ,  631706.18485559, 1348334.51405397,
        417903.59354908,  403955.56695882,  227709.35737831,
        279148.68383132,  411782.25390652,  209265.95028701,
        481603.36967418,  526775.50167833,  409952.73235535,
        439374.76789904,  731361.96941413,  684082.47745432,
       1172875.89432597,  273366.49819547,  428810.57813976,
        214372.73112979,  453033.48306783,  314216.42114377,
        420374.03169884,  723958.12673518,  822837.28415959,
        731468.36851891,  609406.64696116,  611793.62488989,
        688733.27429982,  681762.18778142, 1065349.20308034,
        297103.86193502,  332247.12526376,  745500.00331315,
        390927.57834852,  564742.29195177,  497650.33688503,
        439224.28290036,  398245.13435277,  458158.74008707,
        449872.16725989,  451512.1362437 ,  317880.6426594 ,
        189527.55130746,  523752.34745436,  730907.19713387,
        438402.63186126,  405697.55438104,  440466.89990897,
        614293.96768515,  500312.13216871,  212278.31196108,
        552883.87990062,  505993.57831116, 1090940.49167592,
        590481.29207538,  811916.69471936,  732082.51068663,
        422220.8644956 ,  381450.02626037,  495726.99591284,
        300586.02769085,  731207.25912407,  323105.24199385,
        206557.53757112,  522373.40014477,  423157.22820235,
        607631.06889819,  565341.41966384,  239878.3061813 ,
        395192.19208271, 1014385.79095894,  458064.15375105,
        286420.01056183,  707353.15874706,  770590.41636119,
        346452.82366152,  407177.93996286,  438622.41704723,
        326124.69645467,  493028.74608395,  742347.3912043 ,
        208569.52019584,  603189.05322252,  407490.15341501,
        548954.27809988,  629929.5867167 ,  718038.5403965 ,
        422033.88099441,  559142.59869432,  939694.24046519,
        436509.453124  ,  416091.24987748,  493859.67986313,
        452502.96341003,  511344.48186187,  502954.30074423,
        189919.11869068, 1049783.56521354,  429429.51240614,
       1073083.64634395,  549354.19381635,  685795.32141672,
        438452.32326615,  300327.24977433,  306503.96568306,
        494572.38644202,  614943.88943392,  632946.43077652,
        466775.6364636 ,  327839.87606076,  540604.4080697 ,
        253640.62359114,  605881.41221695,  543573.58649244,
        372413.31101354,  626564.46219492,  695932.91905715,
        481487.14080817,  623348.58302442,  418005.10061228,
        486333.74660188,  403250.65944119,  551683.3215723 ,
        470596.60900452,  409705.47933989,  487171.27665999,
        429399.82354227,  795663.57590413,  374614.85483603,
        242723.18025053,  526581.84200928,  895632.59905974,
        721051.36373869,  183051.24800182,  317383.44189457,
        434292.15172853,  202260.08221345,  482438.47805342,
       1438549.68519825,  387557.39871486,  272302.35815221,
        367149.26449776,  746281.50899985,  294578.95302349,
        749374.76454811,  571109.0034662 , 1027484.8151378 ,
        688892.94908772,  257603.94595985,  410116.18009733,
        763952.45809238,  786118.55893847,  437893.4684543 ,
        448894.43105805,  804849.87659647,  298325.17123467,
        744258.66769599,  702156.70288076,  407295.81456179,
        770061.56305945,  517327.1282004 ,  489944.87863225,
        537898.7550462 ,  629907.13303493,  493438.2728113 ,
       1005476.07230238, 1172173.17170583,  818304.01046913,
        437167.20455056,  560987.64865335, 1817981.50124413,
        567263.71967374, 1400693.71486615,  942608.0509432 ,
        693081.86931319,  658655.30098252,  215440.25102772,
        387105.64373938,  380651.24542514,  356214.48396367,
        386769.3609899 ,  239522.6067734 ,  840218.51101309,
        231860.95819454,  605757.48664882,  755726.61119951,
        428056.74091429,  471230.69752607,  434741.68613764,
        693878.47489363,  468624.55671953,  145438.01384803,
        691853.23131628,  300997.05757003,  347219.69148178,
        380242.76377117,  306188.05833545,  620037.49492273,
        204081.1170355 ,  337110.09771362,  539724.99797521,
        515774.23716567,  524134.14632028,  645273.58209339,
        172108.58086363,  507750.25915005,  410029.16268312,
        443131.18231225,  441322.09004176,  204405.45392684,
        659612.42309005,  545264.71316847])

In [21]:
mse = np.mean((prediction - y_test)**2)
print("Mean Squared Error",mse)

Mean Squared Error 986921767056.1467

In [22]:
accurancy = lr.score(X_test,y_test)
accurancy

0.03228385663275568

In [26]:
# Gradient boosting
X1 = data.drop(['date','price','street','city','statezip','country'],axis =1)
y1 = data['price']

In [27]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=42)

In [28]:
xgb_model = xgb.XGBRegressor()
xgb_model.fit(X1_train, y1_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [29]:
y1_pred = xgb_model.predict(X1_test)

In [30]:
mse1 = mean_squared_error(y1_test,y1_pred)
mse

986921767056.1467

In [33]:
xgb_model.score(y1_pred,X1_test)

XGBoostError: [19:04:47] C:\Users\dev-admin\croot2\xgboost-split_1675461376218\work\src\predictor\cpu_predictor.cc:377: Check failed: m->NumColumns() == model.learner_model_param->num_feature (1 vs. 12) : Number of columns in data must equal to trained model.